spring:
  application:
    name: Technical Project

  datasource:
    url: jdbc:postgresql://localhost:5432/Technical
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_index_ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2crewmember10@gmail.com
    password: yktj ipmw qbtg swnp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    port: 6379
    host: localhost

WAPI: "https://api.weatherstack.com/current?access_key=KEY&query=location"


api.prefix: /api/v1

auth:
  token:
    jwtSecret: G7K2Q9L1M5Z8X4C6P0B3R7T9H2Y5N8D1V4S0F6J3W7U9A2