spring:
  application:
    name: Technical Project

  datasource:
    url: jdbc:postgresql://localhost:5432/Technical
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database:
      platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        auto_index_ddl: true

api.prefix: /api/v1

auth:
  token:
  jwtSecret: G7K2Q9L1M5Z8X4C6P0B3R7T9H2Y5N8D1V4S0F6J3W7U9A2